/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkConfetteRouteImport } from './routes/work.confette'
import { Route as WorkGlownRouteImport } from './routes/work.glown'
import { Route as WorkJuyonnaRouteImport } from './routes/work.juyonna'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkConfetteRoute = WorkConfetteRouteImport.update({
  id: '/work/confette',
  path: '/work/confette',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGlownRoute = WorkGlownRouteImport.update({
  id: '/work/glown',
  path: '/work/glown',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkJuyonnaRoute = WorkJuyonnaRouteImport.update({
  id: '/work/juyonna',
  path: '/work/juyonna',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/confette': typeof WorkConfetteRoute
  '/work/glown': typeof WorkGlownRoute
  '/work/juyonna': typeof WorkJuyonnaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/confette': typeof WorkConfetteRoute
  '/work/glown': typeof WorkGlownRoute
  '/work/juyonna': typeof WorkJuyonnaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/confette': typeof WorkConfetteRoute
  '/work/glown': typeof WorkGlownRoute
  '/work/juyonna': typeof WorkJuyonnaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work/confette' | '/work/glown' | '/work/juyonna'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work/confette' | '/work/glown' | '/work/juyonna'
  id: '__root__' | '/' | '/work/confette' | '/work/glown' | '/work/juyonna'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkConfetteRoute: typeof WorkConfetteRoute
  WorkGlownRoute: typeof WorkGlownRoute
  WorkJuyonnaRoute: typeof WorkJuyonnaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/confette': {
      id: '/work/confette'
      path: '/work/confette'
      fullPath: '/work/confette'
      preLoaderRoute: typeof WorkConfetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/glown': {
      id: '/work/glown'
      path: '/work/glown'
      fullPath: '/work/glown'
      preLoaderRoute: typeof WorkGlownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/juyonna': {
      id: '/work/juyonna'
      path: '/work/juyonna'
      fullPath: '/work/juyonna'
      preLoaderRoute: typeof WorkJuyonnaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkConfetteRoute: WorkConfetteRoute,
  WorkGlownRoute: WorkGlownRoute,
  WorkJuyonnaRoute: WorkJuyonnaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
